import 'package:flutter/material.dart';

class ContraColors {
  static const Color persianBlue = Color(0xFF1947E6);
  static const Color white = Color(0xFFFFFFFF);
  static const Color athensGray = Color(0xFFF4F5F7);
  static const Color lighteningYellow = Color(0xFFFFBD12);
  static const Color flamingo = Color(0xFFF95A2C);
  static const Color black = Color(0xFF000000);
  static const Color woodSmoke = Color(0xFF18191F);
  static const Color trout = Color(0xFF474A57);
  static const Color santasGray = Color(0xFF969BAB);
  static const Color selago = Color(0xFFE9E7FC);
  static const Color carribeanGreen = Color(0xFF00C6AE);
  static const Color santasGray10 = Color(0xFF9FA4B4);
  static const Color dandelion = Color(0xFFFFD465);
  static const Color caribbeanColor = Color(0xFF00C6AE);
  static const Color pastelPink = Color(0xFFFFC7DE);
  static const Color pinkSalmon = Color(0xFFFF89BB);
  static const Color athenGray = Color(0xFFF4F5F7);
  static const Color bareleyWhite = Color(0xFFFFF4CC);
  static const Color fairPink = Color(0xFFFFE8E8);
  static const Color foam = Color(0xFFD6FCF7);
  static const Color lavandarBush = Color(0xFFFFF3F8);
  static const Color monaLisa = Color(0xFFFF9692);
  static const Color athens = Color(0xFFEEEFF4);
  static const Color turquoiseBlue = Color(0xFF61E4C5);
}

const persianBlue = Color(0xFF1947E6);
const white = Color(0xFFFFFFFF);
const athensGray = Color(0xFFF4F5F7);
const lighteningYellow = Color(0xFFFFBD12);
const flamingo = Color(0xFFF95A2C);
const black = Color(0xFF000000);
const woodSmoke = Color(0xFF18191F);
const trout = Color(0xFF474A57);
const santasGray = Color(0xFF969BAB);
const selago = Color(0xFFE9E7FC);
const carribeanGreen = Color(0xFF00C6AE);
const santasGray10 = Color(0xFF9FA4B4);
const dandelion = Color(0xFFFFD465);
const caribbeanColor = Color(0xFF00C6AE);
const pastelPink = Color(0xFFFFC7DE);
const pinkSalmon = Color(0xFFFF89BB);
const athenGray = Color(0xFFF4F5F7);
const bareleyWhite = Color(0xFFFFF4CC);
const fairPink = Color(0xFFFFE8E8);
const foam = Color(0xFFD6FCF7);
const lavandarBush = Color(0xFFFFF3F8);
const monaLisa = Color(0xFFFF9692);
const athens = Color(0xFFEEEFF4);
const turquoiseBlue = Color(0xFF61E4C5);
